export default {
    weekDays: [
        'Sn',
        'Mn',
        'Td',
        'Wd',
        'Th',
        'Fr',
        'St',
    ],
    months: [
        'January',
        'February',
        'Martha',
        'April',
        'May',
        'June',
        'July',
        'Augusta',
        'September',
        'October',
        'November',
        'December',
    ],
};
